### ISSUE TITLE
There will be conflicts with the More Culling mod

### ISSUE THREAD

**Issue by MCSmallCai** [IMB11/xanders-sodium-options#10]
There will be conflicts with the More Culling mod. When opening the sodium video setting interface, the game will crash back

**Comment by isXander** [comment]
Can you send logs?

**Comment by MCSmallCai** [comment]
mod:fabric-api-0.70.0+1.19.2
&nbsp; &nbsp; &nbsp; &nbsp;moreculling-1.19.1-0.12.3
&nbsp; &nbsp; &nbsp; &nbsp;sodium-fabric-mc1.19.2-0.4.4+build.18
&nbsp; &nbsp; &nbsp; &nbsp;xanders-sodium-options-1.0.2-fabric-1.19.2
&nbsp; &nbsp; &nbsp; &nbsp;YetAnotherConfigLib-1.7.1
over


Xuan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "isXander/xanders-sodium-options"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月30日(星期五) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [isXander/xanders-sodium-options] There will be conflicts with the More Culling mod (Issue #10)





 
Can you send logs?

**Comment by DadoIrie** [comment]
Not even a "more culling" conflict

sodium-fabric-mc1.19.2-0.4.4+build.18.jar
xanders-sodium-options-1.0.2-fabric-1.19.2.jar (Added)
YetAnotherConfigLib-2.2.0-for-1.19.2.jar

https://mclo.gs/oYIztzJ
