### ISSUE TITLE
Depends on Fabric Loader 0.16.+?

### ISSUE THREAD

**Issue by notrohit1702** [IMB11/xanders-sodium-options#29]
![Dependency resolution screen](https://github.com/user-attachments/assets/80a120cf-b264-47bd-92de-ec8405ea7a86)

The error above is displayed when launching with the following installed:
- Minecraft 1.21.1
- Fabric Loader 0.16.9
- [Fabric API 0.109.0](https://modrinth.com/mod/fabric-api/version/0.109.0+1.21.1)
- [Sodium 0.6.0](https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.0-fabric)
- [Xander's Sodium Options 2.2.0](https://modrinth.com/mod/xanders-sodium-options/version/2.2.0+1.21.1)
- [YetAnotherConfigLib (YACL) 3.6.1](https://modrinth.com/mod/yacl/version/3.6.1+1.21-fabric)

I'm not sure as to what is meant by `Fabric Loader 0.16.+`, wouldn't that include `0.16.9`?

**Comment by IMB11** [comment]
This is fixed in the recent hotfix.
