### ISSUE TITLE
Incompatability

### ISSUE THREAD

**Issue by XBHS5** [IMB11/xanders-sodium-options#31]
Hello,
I love using Reese's sodium options, and I found your mod and wanted to test it, but when I tried to launch the game, Fabric Loader said "Replace mod 'Xander's Sodium Options' (xanders-sodium-options) 2.3.0+1.21.4 with any version that is compatible with:
  --reeses-sodium-options 1.8.1+mc1.21.4"

**Comment by IMB11** [comment]
Reeses' Sodium Options will never be compatible, uninstall Reese's Sodium Options.
