### ISSUE TITLE
EntityViewDistance compat

### ISSUE THREAD

**Issue by EysseW** [IMB11/xanders-sodium-options#5]
No more culling, as it is not present in my mods folder. I am using 1.1.

https://crashy.net/TmqvL2SHd4JLB1x7RsNx
I have A LOT of mods, so troubleshooting might be hard. I could try, but I haven't got more time to do so today.

**Comment by isXander** [comment]
EntityViewDistance mod. Will add compat

**Comment by EysseW** [comment]
Amazing! Thanks!
