### ISSUE TITLE
Crash new version of More Culling

### ISSUE THREAD

**Issue by lostopkk** [IMB11/xanders-sodium-options#8]
https://github.com/fxmorin/MoreCulling/issues/116

**Comment by VinnyStalck** [comment]
On minecraft 1.19.2 , crashes occurs with [moreculling v0.12.2+](https://github.com/fxmorin/MoreCulling/releases/tag/v0.12.2-1.19)

**Comment by isXander** [comment]
This is due to moreculling renaming their sodium option implementation class. I'll fix this.

**Comment by Redd56** [comment]
Still crashing on 1.19.2

**Comment by isXander** [comment]
Because you're on 1.19.2, not 1.19.3, where this was fixed.

**Comment by Redd56** [comment]
Could you pretty please backport the fix, a ton of mods still havent updated to 1.19.3 (prettymuch most content mods like byg, better x, etc) and xso is really nice. Id revert more culling but there was a major crash issue where any sign it tried to cull period just crashed the game

**Comment by haronv99** [comment]
please🙏, I say the same @isXander

**Comment by k0Yq** [comment]
There will be a backport of this fix to 1.19.2? 1.19.3 and 1.19.4 are lacking alot of mods...
