### ISSUE TITLE
[1.19.3] - Crash when clicking on "Video Settings" and when using "BSVSB"

### ISSUE THREAD

**Issue by ghost** [IMB11/xanders-sodium-options#9]
> ### [Better Sodium Video Settings Button](https://modrinth.com/mod/better-sdoium-video-settings-button/version/3.0.2-1.19.3) [BSVSB] causes a crash when right clicking on "Sodium Video Settings".
> ## I do not believe this is causing the issue since this also happens without BSVSB
> - # | {mclo.gs} (With BSVSB) - Crash-log | **https://mclo.gs/yPrOGbf**
>
> - # {mclo.gs} (WIthout BSVSB) - Crash-log | **https://mclo.gs/BmO3lhp**

**Comment by isXander** [comment]
This is due to YACL being too new. I will release update to XSO shortly.

**Comment by Mark1ed** [comment]
same but on 1.19.2 without bsvsb
[crash-2023-02-23_22.16.21-client.txt](https://github.com/isXander/xanders-sodium-options/files/10818079/crash-2023-02-23_22.16.21-client.txt)

**Comment by ghost** [comment]
@isXander Has been busy with another project lately so I have no idea when they will be able to help you out. Sorry.
